apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: argo-nginx
  name: argo-nginx
spec:
  containers:
  - image: nginx
    name: argo-nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
