apiVersion: v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dep2
spec:
  containers:
  - image: nginx
    name: argo-nginx
  - image: alpine
    name: alpine-linux
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
