apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dep3
  name: dep3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dep3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dep3
    spec:
      containers:
      - image: alpine
        name: alpine
        command: ["sh", "-c", "sleep 900"]
      - image: nginx
        name: nginx
        resources: {}
status: {}
